### ISSUE TITLE
Feature Request: Highlight Guides

### ISSUE THREAD

**Issue by spongessuck** [lkcampbell/brackets-indent-guides#18]
It'd be nice if the guides highlighted along with the block enclosure.

**Comment by joepie91** [comment]
+1

**Comment by fraklo** [comment]
+1

**Comment by lkcampbell** [comment]
Hi all,

I appreciate the enthusiasm for Indent Guides ideas and all of your downloads and ideas.

Unfortunately, I think this idea requires derived data that is not supplied from within the CodeMirror tokenizer model.

To summarize, I have no access to indent levels from within a given line. I really wish I did but I don't.

I'm moving this issue to my `Code Challenges` area. If you all have ideas how to do this, please let me know. I would love to fix a multitude of these types of problems and am always looking for someone to help. Until then, gotta close it as  `Code Challenge`.

If I have misunderstood the request, let me know via email or comments.
