### ISSUE TITLE
indent softwraps

### ISSUE THREAD

**Issue by DanielPintilei** [lkcampbell/brackets-indent-guides#22]
it would be nice if the guides would not be interrupted with https://github.com/scriptin/brackets-indent-softwraps active

**Comment by lkcampbell** [comment]
@DanielPintilei The indent guides extension works by adding a style to white space characters, (i.e. tab or space characters) making them visible. The soft wrap extension adds padding to the style, giving the illusion that there are whitespace characters, where there are no characters. Without characters to stylize indent guides do not show up. This is similar to this issue:

https://github.com/lkcampbell/brackets-indent-guides/issues/16

Not currently fixable with the CodeMirror Overlay system. I am closing as a code challenge.
