### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by mikaeljorhult** [lkcampbell/brackets-indent-guides#28]
I'd be happy to help with a Swedish translation of the extension.

**Comment by lkcampbell** [comment]
@mikaeljorhult, sounds good. I will get the preference strings rewritten to be more concise in English and check in the new strings this weekend.

**Comment by lkcampbell** [comment]
@mikaeljorhult, all the translatable strings are in. Feel free to translate whenever you can. Thanks.

**Comment by lkcampbell** [comment]
Also, let me know if I missed anything. This is the first time I have done translation code. Thanks.

**Comment by lkcampbell** [comment]
@mikaeljorhult, when you get to the "solid" and "dotted" values for guide style, can you put the swedish translation in parentheses next to the english words? See DESCRIPTION_GUIDE_STYLE in https://github.com/tweakimp/brackets-indent-guides/blob/b54daec8daa0a8341918b06ce2eb878c75ea0a49/nls/de/strings.js as an example.

**Comment by mikaeljorhult** [comment]
Okay, I'll get right to it. Will keep the solid/dotted values in mind.

**Comment by mikaeljorhult** [comment]
I've opened a pull request (#31) with the translated strings.

**Comment by lkcampbell** [comment]
Merged. Closing as fixed in version 1.3.9.
