### ISSUE TITLE
Issue With indentation of Switch Case statement, after new update it's not working fine.

### ISSUE THREAD

**Issue by mejainankit** [lkcampbell/brackets-indent-guides#32]
After new update of Indent Guide extension, the indentation of switch case statement in my brackets editor is not working fine. (For Javascript Code)

**Comment by tweakimp** [comment]
Can you provide a screenshot?

**Comment by mejainankit** [comment]
![a](https://cloud.githubusercontent.com/assets/7077837/25373016/94910990-29b5-11e7-8578-2c4c560ee852.png)

I am not sure this happens due to this extension? Please check and fix the same, if this is due to brackets-indent-guides extension.

**Comment by tweakimp** [comment]
Can you list your other extensions?
To me it looks like you or another extension placed the bracket there and not two tabs to the left.
The indentation is wrong,  not the indentation guide.

**Comment by lkcampbell** [comment]
@mejainankit, nothing in the new updates affects how the indent guides work. It's all language translation.

Try `Debug > Reload Without Extensions` and I think you will find that the indentation behaves the same.

Either way, let me know.

**Comment by lkcampbell** [comment]
@mejainankit, actual, even better, disable the Indent Guides extensions and see if the problem still exists. You can disable extensions individually as well and see if you can pinpoint a specific extension or if the problem exists in the core prodcut.

**Comment by lkcampbell** [comment]
Okay, I see you already filed a core product issue at https://github.com/adobe/brackets/issues/13338. Closing as invalid Indent Guides bug.
